@host = localhost:8080

POST http://{{host}}/api/user/register HTTP/1.1
content-type: application/json

{
    "username": "bambangsantoso",
    "email" : "bambangsantoso112@gmail.com",
    "password": "bangbangsantoso"
}

###
